<?php

namespace InputBundle\Repository;

/**
 * PostFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
